AMR = []
AMR.append({'name': '23S rRNA', 'start': 0, 'end': 2974, 'type': 'nu', \
            'subs': [{'pos': 2145, 'orig': 'A'}, \
                     {'pos': 2146, 'orig': 'A'}]})

AMR.append({'name': 'gyrA', 'type': 'prot', \
            'subs': [{'pos': 86, 'orig': 'N'}, \
                     {'pos': 90, 'orig': 'D'}], \
            'ref': 'MQDNSVNETKNIVEVGIDSSIEESYLAYSMSVIIGRALPDARDGLKPVHRRILYAMHELGLTSKVAYKKSARIVGDVIGKYHPHGDNAVYDALVRMAQDFSMRLELVDGQGNFGSIDGDNAAAMRYTEARMTKASEEILRDIDKDTIDFVPNYDDTLKEPDILPSRLPNLLVNGANGIAVGMATSIPPHRMDEIIDALVHVLENPNAGLDEILEFVKGPDFPTGGIIYGKAGIIEAYKTGRGRVKVRAKVHVEKTKNKEIIVLDEMPFQTNKAKLVEQISDLAREKQIEGISEVRDESDREGIRVVIELKRDAMSEIVLNHLYKLTTMETTFSIILLAIYNKEPKIFTLLELLHLFLNHRKTIIIRRTIFELEKAKARAHILEGYLIALDNIDEIVRLIKTSQSPEAAKNALMERFTLSEIQSKAILEMRLQRLTGLERDKIKEEYQNLLELIDDLNGILKSEDRLNGVVKTELLEVKEQFSSPRRTEIQESYENIDIEDLIANEPMVVSMSYKGYVKRVDLKAYEKQNRGGKGKLSGSTYEDDFIENFFVANTHDILLFITNKGQLYHLKVYKIPEASRIAMGKAIVNLISLAPDEKIMATLSTKDFSDERSLAFFTKNGVVKRTNLSEFESNRSCGIRAIVLDEGDELVSAKVVDKNAKHLLIASHLGIFIKFPLEEVREIGRTTRGVIGIKLNENDFVVGAVVISDDGNKLLSVSENGLGKQTLAEAYRGQSRGGKGVIGMKLTQKTGNLVGVISVDDENLDLMILTASAKMIRVSIKDIRETGRNASGVKLINTADKVMYVNSCPKEEEPENLETSSAQNLFE'})