AMR = []
AMR.append({'name': '23S rRNA (1)', 'start': 445248, 'end': 448222, 'type': 'nu', \
            'subs': [{'pos': 2145, 'orig': 'A'}, \
                     {'pos': 2146, 'orig': 'C'}]})

AMR.append({'name': '23S rRNA (2)', 'start': 1473917, 'end': 1476892, 'type': 'nu', \
            'subs': [{'pos': 2145, 'orig': 'A'}, \
                     {'pos': 2146, 'orig': 'C'}]})

AMR.append({'name': 'gyrA', 'type': 'prot', \
            'subs': [{'pos': 86, 'orig': 'N'}, \
                     {'pos': 90, 'orig': 'D'}], \
            'ref': 'MQDNSVNETKNIVEVGIDSSIEESYLAYSMSVIIGRALPDARDGLKPVHRRILYAMHELGLTSKVAYKKSARIVGDVIGKYHPHGDNAVYDALVRMAQDFSMRLELVDGQGNFGSIDGDNAAAMRYTEARMTKASEEILRDIDKDTIDFVPNYDDTLKEPDILPSRLPNLLVNGANGIAVGMATSIPPHRMDEIIDALVHVLENPNAGLDEILEFVKGPDFPTGGIIYGKAGIIEAYKTGRGRVKVRAKVHVEKTKNKEIIVLDEMPFQTNKAKLVEQISDLAREKQIEGISEVRDESDREGIRVVIELKRDAMSEIVLNHLYKLTTMETTFSIILLAIYNKEPKIFTLLELLHLFLNHRKTIIIRRTIFELEKAKARAHILEGYLIALDNIDEIVRLIKTSQSPEAAKNALMERFTLSEIQSKAILEMRLQRLTGLERDKIKEEYQNLLELIDDLNGILKSEDRLNGVVKTELLEVKEQFSSPRRTEIQESYENIDIEDLIANEPMVVSMSYKGYVKRVDLKAYEKQNRGGKGKLSGSTYEDDFIENFFVANTHDILLFITNKGQLYHLKVYKIPEASRIAMGKAIVNLISLAPDEKIMATLSTKDFSDERSLAFFTKNGVVKRTNLSEFESNRSCGIRAIVLDEGDELVSAKVVDKNAKHLLIASHLGIFIKFPLEEVREIGRTTRGVIGIKLNENDFVVGAVVISDDGNKLLSVSENGLGKQTLAEAYRGQSRGGKGVIGMKLTQKTGNLVGVISVDDENLDLMILTASAKMIRVSIKDIRETGRNASGVKLINTADKVMYVNSCPKEEEPENLETSSAQNLFE'})